<?php
$negozio=[
    new Food(
        'assets\dog_food.jpg',
        'Ultima affinity',
        'cane',
        '22 euro',
        'è buono per il vostro cane Carlino che sorride',
        'Ultima',
        'Salmone',
        '3 anni',
    ),
    new Food(
        'assets\cibo_gatti.jpg',
        'whiskas',
        'gatti',
        '20 euro',
        'è buono per il vostro gatto che vi guarda male',
        'whiskas',
        'Tonno',
        '1+ anni',
    ),
    new Toys(
        '.\assets\cartone.jpg',
        'cartone',
        'gatti',
        '3 euro',
        'il gioco più amoato dai gatti',
        'cartone',
        'Marrone',
        '0+ anni',
    ),
    new Toys(
        '.\assets\frisbee.jpg',
        'Frisbee',
        'cani',
        '6 euro',
        'il gioco più amoato dai cani',
        'Freethrow',
        'Viola',
        '1+ anni',
    ),
    new Crates(
        '.\assets\gabbia_cani.jpg',
        'kennel',
        'cani',
        '26 euro',
        'Gabbia regolabile per cani',
        'kernel',
        'regolabile',
        '0+ anni',
    ),new Crates(
        '.\assets\gabbia_gatto.jpg',
        'gabbia comoda',
        'gatti',
        '42 euro',
        'la gabbia più comoda per il vostro cane',
        'Comfy cages',
        'Grigio',
        'ferro',
    ),
]
?>